MySite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import  static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('', include('users.urls')),
    path('', include('PythonCompiler.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='posts'),

    path('post/create/', views.create_post, name='post-create'),
    path('post/edit/<int:id>/', views.edit_post, name='post-edit'),
    path('post/delete/<int:id>/', views.delete_post, name='post-delete'),

    path('task/create/', views.create_task, name='task-create'),
    path('task/edit/<int:id>/', views.edit_task, name='task-edit'),
    path('task/delete/<int:id>/', views.delete_task, name='task-delete'),

    path('course/create/', views.create_course, name='course-create'),
    path('course/edit/<int:id>/', views.edit_course, name='course-edit'),
    path('course/delete/<int:id>/', views.delete_course, name='course-delete'),

    path('solution/create/', views.create_solution, name='solution-create'),
    path('solution/edit/<int:id>/', views.edit_solution, name='solution-edit'),
    path('solution/delete/<int:id>/', views.delete_solution, name='solution-delete'),

    path('about/', views.about, name='about'),

    path('math/', views.math, name='math'),
    path('math-task/', views.math_task, name='math-task'),

    path('phisics/', views.phisics, name='phisics'),
    path('phisics-task/', views.phisics_task, name='phisics-task'),

    path('it/', views.it, name='it'),
    path('it-task/', views.it_task, name='it-task'),

    path('task-list/', views.task_list, name='task-list'),
    path('course-list/', views.course_list, name='course-list'),

    path('task/<int:id>/', views.task, name='task'),

    path('profile/', views.Profile, name='profile')
]

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

#python manage.py makemigrations
#python manage.py migrate
#python manage.py createsuperuser

def user_directory_path(instance, filename):
    return '{0}/{1}/{2}/user_{3}/{4}'.format(instance.index, instance.clas, instance.chapter_title, instance.user.id, filename)



class Post(models.Model):
    title = models.CharField(max_length=120)
    content = models.TextField()
    index = models.CharField(max_length=1)
    published_at = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(User, on_delete=models.CASCADE)


    def __str__(self):
        return self.title


    class Meta:
        ordering = ['-published_at']

class Task(models.Model):
    title = models.CharField(max_length=120)
    chapter_title = models.CharField(max_length=120)
    upload = models.FileField(upload_to=user_directory_path)
    content = models.TextField()
    author = models.CharField(max_length=120)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    index = models.CharField(max_length=1)
    clas = models.CharField(max_length=2)
    published_at = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.title


    class Meta:
        ordering = ['-published_at']

class Solution(models.Model):
    title = models.CharField(max_length=120)
    upload = models.ImageField(upload_to=user_directory_path)
    content = models.TextField()
    author = models.CharField(max_length=120)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    rate_count = models.IntegerField()
    rate_sum = models.IntegerField()
    task = models.ForeignKey('Task', on_delete=models.CASCADE)
    published_at = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.title


    class Meta:
        ordering = ['-published_at']

class Comment(models.Model):
    title = models.CharField(max_length=120)
    upload = models.ImageField(upload_to=user_directory_path)
    content = models.TextField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    solution = models.ForeignKey('Solution', on_delete=models.CASCADE)
    published_at = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.title


    class Meta:
        ordering = ['-published_at']

class Course(models.Model):
    title = models.CharField(max_length=120)
    upload = models.ImageField(upload_to=user_directory_path)
    content = models.TextField()
    author = models.CharField(max_length=120)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    index = models.CharField(max_length=1)
    rate_count = models.IntegerField()
    rate_sum = models.IntegerField()
    published_at = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.title


    class Meta:
        ordering = ['-published_at']

blog/forms.py
from django.forms import ModelForm
from .models import Post, Task, Solution, Comment, Course
from django import forms

class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = [
        'title',
        'content',
        'index'
        ]


class TaskForm(ModelForm):
    class Meta:
        model = Task
        fields = [
        'title',
        'content',
        'author',
        'upload',
        'index',
        'clas',
        'chapter_title'
        ]
'''
{
'title': ['qwe'],
'content': ['qwe'],
'author': ['qwe'],
'upload': ['Scan_0290_FKoMIP0.jpg'],
'index': ['i'],
'clas': ['7'],
'chapter_title': ['Тема1']
}
'''
class SolutionForm(ModelForm):
    class Meta:
        model = Solution
        fields = [
        'title',
        'upload',
        'content',
        'author'
        ]

class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = [
        'title',
        'upload',
        'content'
        ]

class CourseForm(ModelForm):
    class Meta:
        model = Course
        fields = [
        'title',
        'upload',
        'content',
        'author',
        'index'
        ]

blog/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic.list import ListView
from django.core.files.storage import FileSystemStorage
from django.contrib.auth.decorators import  login_required
from django.contrib import messages
from .models import Post, Task, Solution, Comment, Course
from .forms import PostForm, TaskForm, SolutionForm, CommentForm, CourseForm
from django.http import HttpResponse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


def home(request):
    return render(request, 'blog/home.html')

def it(request):
    posts = Post.objects.filter(index='i')
    context = {
        'posts': posts,
        'group': request.user.groups.all()
    }
    return render(request, 'blog/it.html', context)

def it_task(request):
    posts = Post.objects.filter(index='i')
    context = {
        'posts': posts,
        'group': request.user.groups.all()
    }
    return render(request, 'blog/it_task.html', context)

def phisics(request):
    posts = Post.objects.filter(index='p')
    context = {
        'posts': posts,
        'group': request.user.groups.all()
    }
    return render(request, 'blog/phisics.html', context)

def phisics_task(request):
    posts = Post.objects.filter(index='p')
    context = {
        'posts': posts,
        'group': request.user.groups.all()
    }
    return render(request, 'blog/phisics_task.html', context)

def math(request):
    posts = Post.objects.filter(index='m')
    context = {
        'posts': posts,
        'group': request.user.groups.all()
    }
    return render(request, 'blog/math.html', context)

def math_task(request):
    posts = Post.objects.filter(index='m')
    context = {
        'posts': posts,
        'group': request.user.groups.all()
    }
    return render(request, 'blog/math_task.html', context)

def about(request):
    return render(request, 'blog/about.html')

def course_list(request):
    template = 'blog/course_list.html'
    template_page = 'blog/course_list_page.html'
    sub = request.GET.get('s')
    courses = Course.objects.filter(index = sub)
    paginator = Paginator(courses, 5)
    page = request.GET.get('page')
    courses_only = request.GET.get('courses_only')
    try:
        courses = paginator.page(page)
    except PageNotAnInteger:
        courses = paginator.page(1)
    except EmptyPage:
        if courses_only:
            return HttpResponse('')
        courses = paginator.page(paginator.num_pages)
    context = {
    'courses': courses,
    'group': request.user.groups.all(),
    'sub': sub,
    }
    if courses_only:
        return render(request, template_page, context)
    return render(request, template, context)

@login_required
def Profile(request):
    tasks = Task.objects.filter(user=request.user.id)
    context = {
        'tasks': tasks,
        'group': request.user.groups.all()[:1].get()
    }
    return render(request, 'blog/profile.html', context)

def task_list(request):
    template = 'blog/task_list.html'
    template_page = 'blog/task_list_page.html'
    sub = request.GET.get('s')
    clas = request.GET.get('c')
    theme = request.GET.get('n')
    tasks = Task.objects.filter(index = sub, clas = clas, chapter_title = theme)
    paginator = Paginator(tasks, 5)
    page = request.GET.get('page')
    tasks_only = request.GET.get('tasks_only')
    try:
        tasks = paginator.page(page)
    except PageNotAnInteger:
        tasks = paginator.page(1)
    except EmptyPage:
        if tasks_only:
            return HttpResponse('')
        tasks = paginator.page(paginator.num_pages)
    context = {
    'tasks': tasks,
    'group': request.user.groups.all(),
    'sub': sub,
    'clas': clas,
    'theme': theme
    }
    if tasks_only:
        return render(request, template_page, context)
    return render(request, template, context)

def task(request, id):
    queryset = Task.objects.all()
    task = get_object_or_404(queryset, pk=id)
    solutions = Solution.objects.all()
    comments = Comment.objects.all()
    value = request.GET.get('value')
    context = {
    'task': task,
    'solutions': solutions,
    'comments': comments,
    'group': request.user.groups.all(),
    'value': value
    }
    return render(request, 'blog/task.html', context)

@login_required
def delete_post(request, id):
    queryset = Post.objects.all()
    post = get_object_or_404(queryset, pk=id)
    context = {
    'post': post,
    'group': request.user.groups.all()
    }
    if request.method == 'GET':
        return render(request, 'blog/post_confirm_delete.html', context)

    elif request.method == 'POST':
        post.delete()
        messages.success(request, 'The olymp has been deleted successfully.')
        return redirect('posts')


@login_required
def edit_post(request, id):
    queryset = Post.objects.all()
    post = get_object_or_404(queryset, pk=id)
    if request.method == 'GET':
        context = {
        'form': PostForm(instance=post),
        'id': id,
        'group': request.user.groups.all(),
        'title': post.title,
        'content': post.content,
        'lesson': post.index
        }
        return render(request, 'blog/post_form.html', context)

    elif request.method == 'POST':
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            form.save()
            messages.success(request, 'The post has been updated successfully.')
            return redirect('posts')

        else:
            messages.error(request, 'Please correct the following errors:')
            return render(request, 'blog/post_form.html', {'form':form})


@login_required
def create_post(request):
    if request.method == 'GET':
        context = {
        'form': PostForm(),
        'group': request.user.groups.all()
        }
        return render(request, 'blog/post_form.html', context)
    elif request.method == 'POST':
        form = PostForm(request.POST)
        context = {
        'form': form,
        'group': request.user.groups.all()
        }
        if form.is_valid():
            user = form.save(commit=False)
            user.author = request.user
            user.save()
            messages.success(request, 'The post has been created successfully.')
            return redirect('posts')
        else:
            messages.error(request, 'Please correct the following errors:')
            return render(request, 'blog/post_form.html', context)

@login_required
def delete_task(request, id):
    queryset = Task.objects.all()
    task = get_object_or_404(queryset, pk=id)
    context = {
    'task': task,
    'group': request.user.groups.all()
    }
    if request.method == 'GET':
        return render(request, 'blog/task_confirm_delete.html', context)

    elif request.method == 'POST':
        task.delete()
        messages.success(request, 'The task has been deleted successfully.')
        return redirect('posts')

@login_required
def edit_task(request, id):
    queryset = Task.objects.all()
    task = get_object_or_404(queryset, pk=id)
    if request.method == 'GET':
        context = {
        'form': TaskForm(instance=post), 'id': id,
        'group': request.user.groups.all(),
        'title': task.title,
        'chapter_title': task.chapter_title,
        'content': task.content,
        'upload': task.upload,
        'author': task.author,
        'lesson': task.index
        }
        return render(request, 'blog/task_form.html', context)

    elif request.method == 'POST':
        form = TaskForm(request.POST, instance=post)
        if form.is_valid():
            form.save()
            messages.success(request, 'The task has been updated successfully.')
            return redirect('posts')

        else:
            messages.error(request, 'Please correct the following errors:')
            return render(request, 'blog/task_form.html', {'form':form})


@login_required
def create_task(request):
    sub = request.GET.get('s')
    clas = request.GET.get('c')
    theme = request.GET.get('n')
    classes = ["7", "8", "9", "10", "11"]
    themes = ["Тема1", "Тема2", "Тема3", "Тема4"]
    if request.method == 'GET':
        context = {
        'form': TaskForm(),
        'group': request.user.groups.all(),
        'sub': sub,
        'clas': clas,
        'theme': theme,
        'classes': classes,
        'themes': themes
        }
        return render(request, 'blog/task_form.html', context)
    elif request.method == 'POST':
        # form = TaskForm(request.POST)
        form = TaskForm(request.POST, request.FILES)
        for field in form:
            if field.errors:
                print(field.name, field.errors)

        context = {
        'form': form,
        'group': request.user.groups.all(),
        'sub': sub,
        'clas': clas,
        'theme': theme,
        'classes': classes,
        'themes': themes,
        }
        return redirect('posts')
        # if form.is_valid():
        #     user = form.save(commit=False)
        #     user.author = request.user
        #     user.save()
        #     messages.success(request, 'The task has been created successfully.')
        #     return redirect('posts')
        # else:
        #     messages.error(request, 'Please correct the following errors:')
        #     return render(request, 'blog/task_form.html', context)

@login_required
def delete_course(request, id):
    queryset = Course.objects.all()
    course = get_object_or_404(queryset, pk=id)
    context = {
    'course': course,
    'group': request.user.groups.all()
    }
    if request.method == 'GET':
        return render(request, 'blog/course_confirm_delete.html', context)

    elif request.method == 'POST':
        course.delete()
        messages.success(request, 'The course has been deleted successfully.')
        return redirect('posts')

@login_required
def edit_course(request, id):
    queryset = Course.objects.all()
    course = get_object_or_404(queryset, pk=id)

blog/templates/blog/Profile.html
{%load static %}
<!DOCTYPE html>
<html lang="en" >
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="stylesheet" href="{% static 'css/styleload.css' %}" />
        <link rel="stylesheet" href="{% static 'css/profile.css' %}" />
        <script src="{% static 'js/preloader_function.js' %}"></script>
        <link rel="website icon" href="{% static 'imajes/logo.png' %}">
        <title>EazyLearnZone - Profile</title>
    </head>
    <body>
    <div class="preloader">
      <div class="loader"></div>
    </div>
    <div class="background"></div>
    <section class="home">
      <div class="wrapper user">
        <div class="container">
            <p>Имя пользователя: {{request.user.username}}</p>
            <p>Почта: {{request.user.email}} %___Изменить почту___%</p>
            <p>Уровень доступа: {{group}}</p>
            <p>%___Изменить пароль___%</p>
            <a href="{% url 'posts' %}">на главную страницу</a>
        </div>
      </div>
      <div class="list-container">
        <div class="wrapper"><h1>Ваши задания:</h1></div>
        <ul>
        {% for i in tasks%}
          <li class="block">
            <p>Предмет: {% if i.index == "i" %}Программирование{% elif i.index == "p" %}Физика{% elif i.index == "m"%}Математика{% endif %}</p>
            <p>Класс: {{i.clas}}</p>
            <p>Тема: {{i.chapter_title}}</p>
            <p>Номер: {{i.id}}</p>
            <a href="#">ссылка</a>
          </li>
        {% endfor %}
        </ul>
      </div>
      <div class="list-container">
        <div class="wrapper"><h1>Ваши задания:</h1></div>
        <ul>
        {% for i in tasks%}
          <li class="block">
            <p>Предмет: {% if i.index == "i" %}Программирование{% elif i.index == "p" %}Физика{% elif i.index == "m"%}Математика{% endif %}</p>
            <p>Класс: {{i.clas}}</p>
            <p>Тема: {{i.chapter_title}}</p>
            <p>Номер: {{i.id}}</p>
            <a href="#">ссылка</a>
          </li>
        {% endfor %}
        </ul>
      </div>
      <div class="list-container">
        <div class="wrapper"><h1>Ваши задания:</h1></div>
        <ul>
        {% for i in tasks%}
          <li class="block">
            <p>Предмет: {% if i.index == "i" %}Программирование{% elif i.index == "p" %}Физика{% elif i.index == "m"%}Математика{% endif %}</p>
            <p>Класс: {{i.clas}}</p>
            <p>Тема: {{i.chapter_title}}</p>
            <p>Номер: {{i.id}}</p>
            <a href="#">ссылка</a>
          </li>
        {% endfor %}
        </ul>
      </div>
    </section>
  </body>
</html>

blog/templates/blog/about.html
{%load static %}
<!DOCTYPE html>
<html lang="en" >
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static 'css/styleload.css' %}" />
    <link rel="stylesheet" href="{% static 'css/style_about.css' %}" />
    <script src="{% static 'js/preloader_function.js' %}"></script>
    <script src="{% static 'js/app_about.js' %}" defer></script>
    <link rel="website icon" href="{% static 'imajes/logo.png' %}">
    <title>EazyLearnZone - About</title>
  </head>
  <body>
    <div class="preloader">
      <div class="loader"></div>
    </div>
    <div class="background"></div>
    <section class="home">
      <div class="wrapper">
      	<img src="{% static 'imajes/logo.png' %}" class="block logo"/>
      	<p class="block text">
      		Платформа "EasyLearnZone" - образовательный ресурс, объединяющий в себе возможности для подготовки к олимпиадам по физике, программированию и математике. Мы предлагаем пользователям доступ к списку актуальных олимпиад, методическим материалам и заданиям по указанным направлениям, позволяя им расширить свои знания и навыки в удобном формате.
      		<br><br>___создано олимпиадниками для олимпиадников___
      	</p>
				<p class="block preview">
					Основные возможности и преимущества платформы:
				</p>
				<div class="block list">
					<p class="block list-el">
						<span>1</span>Удобный доступ к образовательным материалам: на платформе представлены курсы, методические пособия, разработанные совместно с опытными преподавателями в области физики, программирования и математики.
					</p>
					<p class="block list-el">
						<span>2</span>Встроенный компилятор Python: для удобства пользователей мы предоставляем инструмент для создания программного кода сразу на платформе и автоматической проверки заданий. Это помогает быстро оценить знания и понимание материала.
					</p>
					<p class="block list-el">
						<span>3</span>Бесплатный доступ: мы стремимся сделать знания доступными для всех, поэтому платформа "EasyLearnZone" предоставляет бесплатный доступ к своим ресурсам. Пользователи могут изучать материалы, проходить тестирование и участвовать в обсуждениях без дополнительных затрат.
					</p>
					<p class="block list-el">
						<span>4</span>Система взаимодействия: наша платформа предлагает удобную систему обратной связи между пользователями и администрацией. Вы можете задавать вопросы, делиться своими мыслями и отзывами, получать техническую поддержку от администрации и экспертов.
					</p>
					<p class="block list-el">
						<span>5</span>Разделы с олимпиадами, заданиями и решениями: на платформе "EasyLearnZone" вы найдете специальные разделы, посвященные олимпиадам, заданиям и решениям. Здесь вы сможете проверить свои силы, расширить знания и обсудить методы решений с другими участниками.
					</p>
					<p class="block list-el">
						<span>6</span>Постоянное обновление и добавление контента: мы регулярно обновляем материалы, добавляем новые курсы, пособия, задания и функциональные возможности, чтобы предоставлять пользователям актуальную и интересную информацию.
					</p>
				</div>
				<p class="block block text">
					Начните свой путь к знаниям и успеху прямо сейчас на платформе "EasyLearnZone"! Учите новое, развивайтесь и достигайте целей вместе с нами. Будьте в курсе последних тенденций в олимпиадном направлении, обменивайтесь опытом и вдохновляйтесь успехами других.
					<br><br>Добро пожаловать в сообщество образования и интелектуального роста!
				</p>
      </div>
    </section>
    <a class="button" href="{% url 'posts' %}"><span>Домой</span></a>
  </body>
</html>

blog/templates/blog/course_list.html
{% extends 'baselist.html' %}
{% load static %}

{% block title_name %}
EasyLearnZone - {% if sub == "i" %} Programming
                {% elif sub == "p" %} Phisic
                {% elif sub == "m" %} Mathematic
                {% endif %} courses
{% endblock %}

{% block sbar %}
      <div class="logo-details">
        <i class='bx bxl-c-plus-plus icon'><img src="{% static 'imajes/logo.png' %}" style="width: 27px; height: 27px; filter: invert(100%);"/></i>
        <div class="logo_name">
          {% if sub == "i" %} Programming
          {% elif sub == "p" %} Phisic
          {% elif sub == "m" %} Mathematic
          {% endif %}
        </div>
        <i class='bx bx-menu' id="btn"><img src="{% static 'imajes/3lines.png' %}" style="width: 27px; height: 27px;"/></i>
      </div>
      <ul class="nav-list">
        <li>
          <i class='bx bx-search' style="width: 27px; padding-left: 1px; padding-top: 2px;"><img src="{% static 'imajes/loupe.png' %}" style="width: 27px; height: 27px;"/></i>
          <input type="text" placeholder="Search...">
          <span class="tooltip">Поиск</span>
        </li>
        <li>
          <a href="{% url 'posts' %}">
            <i class='bx bx-user'><img src="{% static 'imajes/home.png' %}" /></i>
            <span class="links_name">На главную страницу</span>
          </a>
          <span class="tooltip">На главную страницу</span>
        </li>
        <li>
          <a
          {% if sub == "i" %} href="{% url 'it-task' %}"
          {% elif sub == "p" %} href="{% url 'phisics-task' %}"
          {% elif sub == "m" %} href="{% url 'math-task' %}"
          {% endif %}
          >
            <i class='bx bx-user'><img src="{% static 'imajes/taskimg.png' %}" style="filter:invert(180);" /></i>
            <span class="links_name">Банк заданий</span>
          </a>
          <span class="tooltip">Банк заданий</span>
        </li>
        {% if sub == "i" %}
        <li>
          <a href="{% url 'compiler' %}">
            <i class='bx bx-user'><img src="{% static 'imajes/itimg1.png' %}" style="filter:invert(180);" /></i>
            <span class="links_name">Песочница</span>
          </a>
          <span class="tooltip">Песочница</span>
        </li>
        {% endif %}
        <li>
          <a
          {% if sub == "i" %} href="{% url 'it' %}"
          {% elif sub == "p" %} href="{% url 'phisics' %}"
          {% elif sub == "m" %} href="{% url 'math' %}"
          {% endif %}
          >
            <i class='bx bx-user'><img src="{% static 'imajes/components.png' %}" style="filter:invert(180);" /></i>
            <span class="links_name">Список олимпиад</span>
          </a>
          <span class="tooltip">Список олимпиад</span>
        </li>
      </ul>
{% endblock %}
{% block content%}
<section class="home">
  <div class="backgroundimgi"></div>
  <div class="wrapper">
    <h2 style="color: #fff; font-size: 35px;">Пособия по {{ course.index }}</h2>
    {% if request.user.is_authenticated and group %}
      <a href="{% url 'course-create' %}?s={{sub}}">добавить пособие</a>
    {% endif %}
    <ul id="course-list">
    {% include 'blog/course_list_page.html' %}
    </ul>
  </div>
</section>

{% endblock %}
{% block domready %}
  var page = 1;
  var emptyPage = false;
  var blockRequest = false;

  window.addEventListener('scroll', function(e) {
    var margin = document.body.clientHeight - window.innerHeight - 200;
    if(window.pageYOffset > margin && !emptyPage && !blockRequest) {
      blockRequest = true;
      page += 1;

      fetch('?s={{ sub }}&courses_only=1&page=' + page)
      .then(response => response.text())
      .then(html => {
        if (html === '') {
          emptyPage = true;
        }
        else {
          var courseList = document.getElementById('course-list');
          courseList.insertAdjacentHTML('beforeend', html);
          blockRequest = false;
        }
      })
    }
  });

  // Launch scroll event
  const scrollEvent = new Event('scroll');
  window.dispatchEvent(scrollEvent);
{% endblock %}

blog/templates/blog/post_confirm_delete.html
{% extends 'basepostform.html' %}
{% block title_name %}EazyLearnZone - Delete Post{% endblock title_name %}
{% block h1 %}Удаление поста{% endblock h1 %}
{% block form %}
    <p>Вы действительно хотите удалить пост "{{post.title}}"?</p>
    <div class="btn">
        <button class="button" type="submit" value="Удалить"><span>Удалить</span></button>
    </div>
    <div class="pass-link">
        <a href="{% url 'posts' %}">Назад</a>
        <i>></i>
    </div>
{% endblock form %}

blog/templates/blog/task_confirm_delete.html
{% extends 'basepostform.html' %}
{% block title_name %}EazyLearnZone - Delete Task{% endblock title_name %}
{% block h1 %}Удаление задания{% endblock h1 %}
{% block form %}
    <p>Вы действительно хотите удалить задание "{{task.title}}"?</p>
    <div class="btn">
        <button class="button" type="submit" value="Удалить"><span>Удалить</span></button>
    </div>
    <div class="pass-link">
        <a href="{% url 'posts' %}">Назад</a>
        <i>></i>
    </div>
{% endblock form %}

blog/templates/blog/task_form.html
{% extends 'basetaskform.html' %}
{% block title_name %}
	EazyLearnZone - {% if id %}Edit{% else %}New{% endif %} Task
{% endblock title_name %}
{% block h1 %}
	{% if id %}Изменение задания{% else %}Новое задание{% endif %}
{% endblock h1 %}
{% block form %}
	<div class="field">
		<label for="id_title">Название</label>
		<input type="text" name="title" cols="20" rows="1" maxlength="120" value="{{ title }}" id="id_title" autocomplete="new-title" autofocus required></div>
	<div class="field">
		<label for="id_content">Условия</label>
		<input type="text" name="content" cols="20" rows="1" id="id_content" value="{{ content }}" autocomplete="new-title" required></div>
	<div class="field">
		<label for="id_author">Автор задания</label>
		<input type="text" name="author" cols="20" rows="1" id="id_author" value="{{ content }}" autocomplete="new-title" required></div>
	<div class="field">
		<label for="id_upload">Изображения к заданию</label>
		<input type="file" name="upload" id="id_upload" required>
	</div>

	<div class="sel">
		<select name="index" class="select" id="id_index" required>
			<option value="">
				<div class="option">
					<i class="fab fa-codepen"></i>
					<label>Предмет</label>
				</div>
			</option>
			<option value="i">
				<div class="option">
				    <i class="fab fa-codepen"></i>
				    <label>Программирование</label>
				</div>
			</option>
			<option value="p">
				<div class="option">
			        <i class="fab fa-codepen"></i>
			        <label>Физика</label>
			    </div>
			</option>
			<option value="m">
				<div class="option">
			        <i class="fab fa-codepen"></i>
			        <label>Математика</label>
			    </div>
			</option>
		</select>
	</div>
	<div class="sel">
		<select name="clas" class="select" id="id_clas" required>
			<option value="">
				<div class="option">
					<i class="fab fa-codepen"></i>
					<label>Класс</label>
				</div>
			</option>
			{% for value_clas in classes %}
			<option value={{value_clas}}>
				<div class="option">
				    <i class="fab fa-codepen"></i>
				    <label>{{value_clas}} класс</label>
				</div>
			</option>
			{% endfor %}
		</select>
	</div>
	<div class="sel">
		<select name="chapter_title" class="select" id="id_chapter_title" required>
			<option value="">
				<div class="option">
					<i class="fab fa-codepen"></i>
					<label>Раздел</label>
				</div>
			</option>
			{% for value_theme in themes %}
			<option value={{value_theme}}>
				<div class="option">
				    <i class="fab fa-codepen"></i>
				    <label>{{value_theme}}</label>
				</div>
			</option>
			{% endfor %}
		</select>
	</div>
	<div class="btn">
		<button class="button" type="submit" value="Save"><span>Save</span></button>
	</div>
{% endblock form %}